apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: central-collector
  namespace: observability
spec:
  mode: deployment
  config: |
    receivers:
      # Logs receiver (for Loki)
      filelog:
        include: [/var/log/containers/*.log]
      
      # Metrics receivers (for Prometheus)
      prometheus:
        config:
          global:
            scrape_interval: 15s
          scrape_configs:
            - job_name: 'kubernetes-pods'
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                  action: keep
                  regex: true
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                  action: replace
                  target_label: __metrics_path__
                  regex: (.+)
                - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
                  action: replace
                  regex: ([^:]+)(?::\d+)?;(\d+)
                  replacement: $1:$2
                  target_label: __address__
      
      # Traces receiver (for Tempo)
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024

    exporters:
      # Logs to Loki
      loki:
        endpoint: "http://loki:3100/loki/api/v1/push"
        labels:
          resource:
            k8s.container.name: "k8s.container.name"
            k8s.pod.name: "k8s.pod.name"
            k8s.namespace.name: "k8s.namespace.name"
      
      # Metrics to Prometheus
      prometheus:
        endpoint: "0.0.0.0:9090"
      
      # Traces to Tempo
      otlp:
        endpoint: "tempo:4317"
        tls:
          insecure: true

    service:
      pipelines:
        logs:
          receivers: [filelog]
          processors: [batch]
          exporters: [loki]
        metrics:
          receivers: [prometheus]
          processors: [batch]
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]