apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    version: 1
    editable: true
  - name: PROMETHEUS
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    version: 1
    editable: true