# demo-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-demo
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
      - name: petclinic
        image: ghcr.io/open-telemetry/opentelemetry-demo/petclinic:latest
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://tempo.observability.svc.cluster.local:4317"
        - name: OTEL_SERVICE_NAME
          value: "petclinic-demo"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  namespace: observability
spec:
  selector:
    app: petclinic
  ports:
  - port: 8080
    targetPort: 8080